export default ScreenType = {
    /**
     * Cannot create value = -1 here
     */
    FROM_PACKAGE_VIEW: 3,
    FROM_USER_PROFILE: 4,
    FROM_TESTING_HISTORY: 5,
    FROM_CONFIRM_WRITING: 6,
    FROM_REGISTER_TESTING: 7,
    FROM_LOGIN: 8,
    FROM_FORGET_PASSWORD: 9,
    FROM_ORDER_HISTORY: 10,
    FROM_LOGIN_SOCIAL: 11,
    FROM_REGISTER: 12,
    FROM_SELLING_VEHICLE_MY_POST: 13,
    FROM_SELLING_VEHICLE_SEEN: 14,
    FROM_SELLING_VEHICLE_GENERAL: 15,
    FROM_HOME_VIEW: 16,
    FROM_CART: 17,
    FROM_ORDERS: 18,
    FROM_SEARCH_SELLING: 19,
    FROM_PRODUCT: 20,
    FROM_SELLING_VEHICLE_DETAIL: 22,
    FROM_SELLING_MY_POST_NEW: 23,
    FROM_NOTIFICATION: 24,
    FROM_BASE_VIEW: 25,
}