export const ErrorCode = {
    ERROR_INIT: -1, //Error for init first
    ERROR_SUCCESS: 0,
    ERROR_COMMON: 1,
    UN_AUTHORIZE: 401,
    NO_CONNECTION: 404,
    INVALID_ACCOUNT: 103,
    USER_ALREADY_REGISTER_EXAM: 105,
    LOGIN_FAIL_USERNAME_PASSWORD_MISMATCH: 102,
    USER_EXIST_TRY_LOGIN_FAIL: 101,
    STUDENT_ID_NOT_EXISTS: 603,
    AUTHENTICATE_REQUIRED: 104,
    USER_HAS_BEEN_DELETED: 106,
    ERROR_SYNCHRONIZED: -1,
    RENEWS_SUCCESS: 700,
    RENEWS_LIMITTED: 701,
    USER_HAS_BEEN_BLOCKED: 107
};