module.exports = {
    onChangeBadger: null,
    gotoBlogDetail: null,
    onStopAudio: null,
    onListItemSelected: null,
    dataCardMember: null,
    onShowCardMember: null,
    location: null,
    isUseCard: true,
    badgeCount: 0,
    openModalBanner: null,
    dataAddress: null,
    onExitApp: null,
    avatarMemberChat: null,
    nameMemberChat: null,
    positionX: 0,
    notifyGPS: true,
    numberUnseen: 0,
    userAdminId: null,
    adminPath: null,
    idUser: null,
    idChoose: 0,
    idGeneralChoose: 0,
    atMessage: null
};
